### PR TITLE
YEL-391

### PR DESCRIPTION
**Pull request by ianrelf**
Updated FTP scripts for SSM data.

### CODE REVIEW

**Review by david-wirelab — DISMISSED** [review]
LGTM

**Comment by tomfitzherbert** [comment]
In the spirit of making this codebase immutable could we please parameterise the key/value inputs for the two ACL scripts?

aclhistory-del.py
aclhistory-edit.py

I would recommend making the script accept command line arguments would be the cleanest method.

https://www.tutorialspoint.com/python/python_command_line_arguments.htm

**Review by tomfitzherbert — CHANGES_REQUESTED** [review]
In the spirit of making this codebase immutable could we please parameterise the key/value inputs for the two ACL and two OAG scripts?

aclhistory-del.py
aclhistory-edit.py
oaghistory-del.py
oaghistory-edit.py

I would recommend making the script accept command line arguments as this would be the cleanest method.

**Comment by ianrelf** [comment]
Hi Tom,
I have edited the helper scripts to accept commandline arguments. 
Please re-review.

**Review by tomfitzherbert — APPROVED** [review]

**Comment by tomfitzherbert** [comment]
Thanks @ianrelf 

I have updated the README files to match the new usage commands.

I would note that the updates to `aclhistory.py` and `oaghistory.py` are unnecessary since these scripts don't expect or accept any command line arguments. However this is a minor point, so happy to push ahead with those like this (given that these will eventually be replaced entirely anyway).

**Pull request merged**
